resources:
- name: my-git-repository
  type: git
  source:
    uri: https://github.com/shinji62/thinkit-gitresource.git
    branch: master


- name: concourse-getting-started
  type: git
  source:
    uri: https://github.com/shinji62/concourse-getting-started.git
    branch: master


jobs:
- name: hello-world
  plan:
  - get: my-git-repository
    trigger: true
  - get: concourse-getting-started
  - task: say-hello
    file: concourse-getting-started/tasks/run-hello-world.yml
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      inputs:
        - name: my-git-repository
      run:
        path: sh
        args:
        - -c
        - |
         cat my-git-repository/hello-thinkit
