resources:
- name: my-git-repository
  type: git
  source:
    uri: https://github.com/shinji62/thinkit-gitresource.git
    branch: master


jobs:
- name: hello-world
  plan:
  - get: my-git-repository
    trigger: true
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      inputs:
        - name: my-git-repository
      run:
        path: sh
        args:
        - -c
        - |
         exit 1
