---
platform: linux
image_resource:
  type: docker-image
  source: {repository: ubuntu}
inputs:
  - name: my-git-repository
run:
  path: sh
  args: 
  - -c
  - |
   cat my-git-repository/hello-thinkit
